import './globals.css';

import type { Metadata } from 'next';

import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';

import { CONFIG } from '@/global-config';
import { LocalizationProvider } from '@/locales';
import { detectLanguage } from '@/locales/server';
import { themeConfig, ThemeProvider } from '@/theme';
import { I18nProvider } from '@/locales/i18n-provider';

import { detectSettings } from '@/components/settings/server';
import { SettingsDrawer, defaultSettings, SettingsProvider } from '@/components/settings';
import { Snackbar } from '@/components/snackbar';

import { AuthProvider } from '@/auth';
import { ChatProvider } from '@/chat';
import { MainLayout } from '@/layouts/main/layout';

// ----------------------------------------------------------------------

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getAppConfig() {
  if (CONFIG.isStaticExport) {
    return {
      lang: 'en',
      i18nLang: undefined,
      cookieSettings: undefined,
      dir: defaultSettings.direction,
    };
  } else {
    const [lang, settings] = await Promise.all([detectLanguage(), detectSettings()]);

    return {
      lang: lang ?? 'en',
      i18nLang: lang ?? 'en',
      cookieSettings: settings,
      dir: settings.direction,
    };
  }
}

// ----------------------------------------------------------------------

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const appConfig = await getAppConfig();

  return (
    <html lang={appConfig.lang} dir={appConfig.dir} suppressHydrationWarning>
      <body>
        <InitColorSchemeScript
          modeStorageKey={themeConfig.modeStorageKey}
          attribute={themeConfig.cssVariables.colorSchemeSelector}
          defaultMode={themeConfig.defaultMode}
        />

        <I18nProvider lang={appConfig.lang}>
          <SettingsProvider
            cookieSettings={appConfig.cookieSettings}
            defaultSettings={defaultSettings}
          >
            <LocalizationProvider>
              <ThemeProvider
                modeStorageKey={themeConfig.modeStorageKey}
                defaultMode={themeConfig.defaultMode}
              >
                <AuthProvider>
                  <ChatProvider>
                    <Snackbar />
                    <SettingsDrawer defaultSettings={defaultSettings} />
                    {children}
                  </ChatProvider>
                </AuthProvider>
              </ThemeProvider>
            </LocalizationProvider>
          </SettingsProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
